version: 1.0.{build}
build: false
platform: x64
image: Visual Studio 2015
clone_folder: c:\wamp64\www\projects\tests
branches:
  only:
    - master

init:
  - SET PATH=c:\php;%PATH%
  - SET COMPOSER_NO_INTERACTION=1
  - SET PHP=1

cache:
  - '%LOCALAPPDATA%\Composer\files'

# install:
  # - ps: Set-Service wuauserv -StartupType Manual
  # - cinst -y php composer
  # - refreshenv
  # - cd c:\tools\php73
  # - copy php.ini-production php.ini /Y
  # - echo date.timezone="UTC" >> php.ini
  # - echo extension_dir=ext >> php.ini
  # - echo extension=php_openssl.dll >> php.ini
  # - echo extension=php_mbstring.dll >> php.ini
  # - echo extension=php_curl.dll >> php.ini
  # - echo memory_limit=3G >> php.ini
  # - cd %APPVEYOR_BUILD_FOLDER%
  # - composer install --no-interaction --no-progress

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  # - vendor\bin\phpunit.bat --verbose
  - cd c:\wamp64\www\2-test-unit\TestUnit\vendor\autoload.php